### ISSUE TITLE
Can I have a transparent extra webview?

### ISSUE THREAD

**Issue by AndersBillLinden** [kunder-lab/cl.kunder.webview#19]
For dialogs, this plugin is excellent, but is there a way to make the background transparent?

```
<body style="background-color:transparent">
</body>
```

seems to have no effect.

**Comment by arturokunder** [comment]
Hi @AndersBillLinden 
In order to achieve this, you will need to change the code.

That change only will take effect on your `html`, but you'll need to change the layout color.

In `Android`, you will have to take a look on [this line of code](https://github.com/kunder-lab/cl.kunder.webview/blob/master/src/android/cl/kunder/webview/WebViewActivity.java#L51):
```java
layoutPrincipal.setBackgroundColor(Color.parseColor("#d9000000"));
```

I don't know if `Android` support transparent layouts on new Activities.
On `iOS`, I don't know if it's possible.
